<a href="https://colab.research.google.com/github/eduruiz00/pytorch-course/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
first_tensor = torch.rand(7, 7)
first_tensor

tensor([[0.0191, 0.1633, 0.2758, 0.3001, 0.3147, 0.3933, 0.1594],
        [0.1581, 0.0015, 0.3151, 0.8930, 0.9949, 0.5506, 0.5216],
        [0.9071, 0.8578, 0.2977, 0.7700, 0.2516, 0.9157, 0.1197],
        [0.6435, 0.5580, 0.8658, 0.6622, 0.5073, 0.0864, 0.1700],
        [0.7285, 0.0876, 0.7406, 0.3480, 0.8249, 0.5324, 0.1520],
        [0.2261, 0.1519, 0.4236, 0.3660, 0.5865, 0.1961, 0.8922],
        [0.9406, 0.5690, 0.4340, 0.1715, 0.0727, 0.7604, 0.8239]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [19]:
# Create another random tensor
second_tensor = torch.rand(1, 7)

# Perform matrix multiplication 
result_multiplication_tensor = torch.matmul(first_tensor, second_tensor.T)
result_multiplication_tensor

tensor([[0.6436],
        [1.4270],
        [2.0196],
        [1.6218],
        [1.6233],
        [1.4482],
        [2.1766]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [20]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
first_tensor_seed0 = torch.rand(7, 7)
second_tensor_seed0 = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(first_tensor_seed0, second_tensor_seed0.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [21]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [24]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

print(tensor_A)
print(tensor_B)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [25]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [27]:
# Find max
print(f'Max: {torch.max(tensor_C)}')

# Find min
print(f'Min: {torch.min(tensor_C)}')

Max: 0.5617256760597229
Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max
print(f"Max index: {torch.argmax(tensor_C)}")

# Find arg min
print(f"Min index: {torch.argmin(tensor_C)}")

Max index: 3
Min index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor_D = tensor_D.squeeze()

# Print out tensors and their shapes
print("Previous tensor:", tensor_D)
print("Previous shape:", tensor_D.shape)
print("\nNew tensor:", squeezed_tensor_D)
print("New shape:", squeezed_tensor_D.shape)

Previous tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Previous shape: torch.Size([1, 1, 1, 10])

New tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
New shape: torch.Size([10])
